### ISSUE TITLE
Measure initialisation fails and crashes with java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by abhaysood** [measure-sh/measure#1174]
# Summary

SDK is crashing when trying to load the native `libmeasure.so` library on certain devices.

The stacktrace looks similar to the one mentioned here: https://github.com/flutter/flutter/issues/37566. This issue also mentions that the crash is not happening on physical devices, which has been true with the initial testing we have done too.

One of the fixes mentioned in multiple similar issues is to add the following to the app  `build.gradle` file, we are yet to verify if this actually fixes the issue or not.

```groovy
defaultConfig {
  ndk {
    abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
  }
}
```

# Stacktrace

### Sample 1
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~-Xt5CwIuqT_vxnlgUZSmgQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmeasure-ndk.so" (new hash type from the future?)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
       at java.lang.System.loadLibrary(System.java:1765)
       at sh.measure.android.NativeBridgeImpl.<clinit>(NativeBridge.kt:26)
       at sh.measure.android.MeasureInitializerImpl.<init>(MeasureInitializer.kt:274)
       at sh.measure.android.Measure.init(Measure.kt:53)
       at sh.measure.android.Measure.init$default(Measure.kt:46)
```

### Sample 2
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/base.apk"],nativeLibraryDirectories=[/data/app/==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmeasure-ndk.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at sh.measure.android.NativeBridgeImpl.<clinit>(NativeBridge.kt:26)
       at sh.measure.android.MeasureInitializerImpl.<init>(MeasureInitializer.kt:274)
       at sh.measure.android.Measure.init(Measure.kt:53)
       at sh.measure.android.Measure.init$default(Measure.kt:46)
```

**Comment by abhaysood** [comment]
[This](https://github.com/measure-sh/measure/pull/1179) should prevent the app from crashing.

Keeping this issue open as the root cause is yet to be reproduced & fixed. When the native library fails to load, ANR tracking will not work.

**Comment by abhaysood** [comment]
One of the root cause for this issue has been found. This is related to supporting 16 KB page sizes: #1173 

This will fix the error: `Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~-Xt5CwIuqT_vxnlgUZSmgQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmeasure-ndk.so" (new hash type from the future?)`

Still investigating the other issue, which is different: `Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/base.apk"],nativeLibraryDirectories=[/data/app/==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmeasure-ndk.so"`

**Comment by abhaysood** [comment]
https://github.com/measure-sh/measure/pull/1211 fixes the issue for Android SDK 35 devices which now support 16KB page sizes. 

We don't see anything we can do to avoid the following for emulators running on x86. Hence closing this issue.
`Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/base.apk"],nativeLibraryDirectories=[/data/app/==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmeasure-ndk.so"`
