### ISSUE TITLE
Fix runtime panic on event ingestion

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#1310]
## Summary

A runtime panic occurs occasionally for some PUT `/events` calls.

## Stacktrace

```
goroutine 4412385 [running]:
runtime/debug.Stack() /usr/local/go/src/runtime/debug/stack.go:26 +0x5e
main.main.CapturePanic.func6.1() /go/src/app/server/middleware.go:87 +0x47
panic({0x14af720?, 0xc015d00c00?}) /usr/local/go/src/runtime/panic.go:785 +0x132
backend/api/event.Exception.GetMethodName(...) /go/src/app/event/event.go:949
backend/api/measure.eventreq.bucketUnhandledExceptions({{0x68, 0x6c, 0x43, 0xc7, 0xf4, 0x4d, 0x48, 0x38, 0xa2, 0xd4, ...}, ...}, ...) /go/src/app/measure/event.go:349 +0x7b6
backend/api/measure.PutEvents(0xc003a1e000) /go/src/app/measure/event.go:2226 +0x1d10
github.com/gin-gonic/gin.(*Context).Next(0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
main.main.ValidateAPIKey.func8(0xc003a1e000) /go/src/app/measure/auth.go:110 +0x212
github.com/gin-gonic/gin.(*Context).Next(0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
main.main.CaptureErrorBody.func7(0xc003a1e000) /go/src/app/server/middleware.go:57 +0xbc
github.com/gin-gonic/gin.(*Context).Next(0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
main.main.CapturePanic.func6(0xc01696dd50?) /go/src/app/server/middleware.go:115 +0x3f
github.com/gin-gonic/gin.(*Context).Next(0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
main.main.CaptureRequest.func5(0xc003a1e000) /go/src/app/server/middleware.go:40 +0x26b
github.com/gin-gonic/gin.(*Context).Next(...) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin.Middleware.func1(0xc003a1e000) /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin@v0.53.0/gintrace.go:82 +0x719
github.com/gin-gonic/gin.(*Context).Next(...) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 +0x6f
github.com/gin-gonic/gin.(*Context).Next(...) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 +0xe5
github.com/gin-gonic/gin.(*Context).Next(...) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001ddd40, 0xc003a1e000) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 +0x892
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001ddd40, {0x3d44500, 0xc0116f8620}, 0xc0116d7b80) /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 +0x1b2 net/http.serverHandler.ServeHTTP({0x3d3d5d0?}, {0x3d44500?, 0xc0116f8620?}, 0x6?) /usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0119a1200, {0x3d467c0, 0xc0000b6630}) /usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1 /usr/local/go/src/net/http/server.go:3360 +0x485
```

**Comment by detj** [comment]
This has been fixed in #1345
